### ISSUE TITLE
Rails 5 incompatibility 

### ISSUE THREAD

**Issue by rousisk** [salesking/sk_sdk#8]
Hi,

We just upgraded to Rails 5 and our integration broke (while using `0.4.0`).

After bumping to the latest version of the gem (`0.4.1`), we now get this error:

```
5: from /home/rousis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activeresource-5.0.0/lib/active_resource/base.rb:935:in `find'
4: from /home/rousis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activeresource-5.0.0/lib/active_resource/base.rb:1027:in `find_every'
3: from /home/rousis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sk_sdk-0.4.1/lib/sk_sdk/ar_patches/ar4/base.rb:28:in `instantiate_collection'
2: from /home/rousis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sk_sdk-0.4.1/lib/sk_sdk/ar_patches/ar4/base.rb:28:in `new'
1: from /home/rousis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activeresource-5.0.0/lib/active_resource/collection.rb:57:in `initialize'
ArgumentError (wrong number of arguments (given 2, expected 0..1))
```

Have you successfully tried with a Rails 5 app and it worked for you?

**Comment by schorsch** [comment]
please check if this fixes your issues. At least it does in my tests. I will bump a new version than.
Thanks for the report!

**Comment by siebertm** [comment]
On it, give me 10minutes!

**Comment by siebertm** [comment]
Awesome @schorsch it works :+1: 

Can we maybe have a quick chat about the support experience we had (after the version bump)?
